### PR TITLE
Duplicate the credential management command as a vendor command

### LINKED ISSUE #526: Failed to load "resident" ssh key generated by OpenSK device
## Expected Behavior
　　After successfully generating the residential ssh keys by `ssh-keygen -t ecdsa-sk -O resident`, the private key should can be load to another computer via the OpenSK devices by `ssh-add -K`, but it failed to load.

## Actual Behavior
　　Generation step on residental key seems to be successful, but when I tried to load the key to anthoer PC, by pluging in the OpenSK device and `ssh-add -K`, it shows 
`Enter PIN for authenticator:` 
`Provider "internal" returned failure -1`
`Unable to load resident keys: invalid format`
　　(the PIN was set correctly.)
　　After enable verbose mode by `ssh-add -K -v`, it shows
`Enter PIN for authenticator:`
`debug1: start_helper: starting /usr/lib/ssh/ssh-sk-helper` 
`debug1: sshsk_load_resident: provider "internal", have-pin`
`debug1: sk_probe: 1 device(s) detected`
`debug1: sk_probe: selecting sk by touch`
`debug1: ssh_sk_load_resident_keys: trying /dev/hidraw5`
`debug1: check_sk_options: option uv is unknown`
`debug1: read_rks: get metadata for /dev/hidraw5 failed: FIDO_ERR_MISSING_PARAMETER`
`debug1: ssh_sk_load_resident_keys: read_rks failed for /dev/hidraw5`
`Provider "internal" returned failure -1`
`debug1: ssh-sk-helper: sshsk_load_resident failed: invalid format`
`debug1: main: reply len 8`
`debug1: client_converse: helper returned error -4`
`Unable to load resident keys: invalid format`
　　which makes me confused.

## Steps to Reproduce the Problem

1. Generate a pair of residental ssh key by `ssh-keygen -t ecdsa-sk -O resident`.
2. Plug the OpenSK device to another PC.
3. Try to load the key generated to that PC `ssh-add -K -v`

## Specifications
- Device: Nordic nRF52840 Dongle
- Version: c6d3f51 of develop branch
- Platform: Arch Linux

　　I would appreciate it if you could do me a favour to solve that problem. Looking forward to your reply on your earliest convenience.

### PR DESCRIPTION
**Pull request by ia0**
This permits to work with libfido2 and thus ssh-add. Fix #526.

### CODE REVIEW

File: src/ctap/command.rs [hunk 1]
```diff
@@ -70,8 +70,12 @@ impl Command {
...
     const _AUTHENTICATOR_VENDOR_FIRST: u8 = 0x40;
     const AUTHENTICATOR_VENDOR_CONFIGURE: u8 = 0x40;
-    const AUTHENTICATOR_VENDOR_UPGRADE: u8 = 0x41;
-    const AUTHENTICATOR_VENDOR_UPGRADE_INFO: u8 = 0x42;
+    // This commands is the same as AUTHENTICATOR_CREDENTIAL_MANAGEMENT but is duplicated as a
+    // vendor command for legacy and compatibility reasons. See
+    // https://github.com/Yubico/libfido2/issues/628 for more information.
+    const AUTHENTICATOR_VENDOR_CREDENTIAL_MANAGEMENT: u8 = 0x41;
+    const AUTHENTICATOR_VENDOR_UPGRADE: u8 = 0x42;
+    const AUTHENTICATOR_VENDOR_UPGRADE_INFO: u8 = 0x43;
```
Comment (kaczmarczyck) [inline src/ctap/command.rs:78]: These numbers have to go into `tools/deploy_partition.py`, it has constants for `OPENSK_VENDOR_UPGRADE` and `OPENSK_VENDOR_UPGRADE_INFO`.
```

**Review by kaczmarczyck — COMMENTED** [review]
Looks good for the fix, but breaks the upgrade script.

File: src/ctap/command.rs (hunk 1 above)
Comment (ia0) [reply src/ctap/command.rs:78]: Thanks! Done.

**Review by sophiel-meow — APPROVED** [review]
it works as expected.

**Review by kaczmarczyck — APPROVED** [review]
