### PR TITLE
Fix user presence by not overwriting error with OK()

### LINKED ISSUE #519: User presence touch timeouts get treated as user presence
## Expected Behavior
When waiting for user presence, a timeout should lead to an error, eg CTAP2_ERR_USER_ACTION_TIMEOUT

## Actual Behavior
Successful response is returned to host.

## Steps to Reproduce the Problem

1.  send a AuthenticatorMakeCredential command
1.  don't touch the buttons

## Specifications

- Version: develop branch
- Platform: linux

### PR DESCRIPTION
**Pull request by liamjm**
Fixes #519 

The key change is in check_user_presence(), where the result of the user_presence().wait_with_timeout() call is now not overwritten unless the subsequent call to send_keepalive_up_needed() returns an error.

Tests added in #520 demonstrate the bug.

### CODE REVIEW

File: src/ctap/mod.rs [hunk 1]
```diff
@@ -349,8 +349,14 @@ fn check_user_presence(env: &mut impl Env, channel: Channel) -> Result<(), Ctap2
         // accordingly, so that all wait_with_timeout invocations are separated by
         // equal time intervals. That way token indicators, such as LEDs, will blink
         // with a consistent pattern.
-        result = send_keepalive_up_needed(env, channel, KEEPALIVE_DELAY);
-        if result.is_err() {
+        let ka_result = send_keepalive_up_needed(env, channel, KEEPALIVE_DELAY);
```
Comment (kaczmarczyck) [inline src/ctap/mod.rs]: "ka" is not a common acronym for me at least, so please spell it out.

File: tools/vendor_hid_test.py [hunk 2]
```diff
@@ -1,7 +1,12 @@
 """These tests verify the functionality of the VendorHID interface."""
-from typing import Dict, Iterable
```
Comment (kaczmarczyck) [inline tools/vendor_hid_test.py]: I will review this file after #520 landed, since the diff should be small? There is not commit with the exact diff.

Comment (liamjm) [reply tools/vendor_hid_test.py]: Yeah, sorry, I didn't base this PR off that one. 

The diff will be small once #520 lands.

**Review by kaczmarczyck — COMMENTED** [review]
#520 is merged!
I had a high-level comment about this PR, but I can't find it, so maybe it got lost:
The fix is in `src/ctap/mod.rs`, so we should be able to write a unit test that catches this bug? Unit tests have value additional to your script since they can be easily automated.

File: tools/vendor_hid_test.py (hunk 2 above)
Comment (liamjm) [reply tools/vendor_hid_test.py]: Done.

**Comment by liamjm** [comment]
> #520 is merged! I had a high-level comment about this PR, but I can't find it, so maybe it got lost: The fix is in `src/ctap/mod.rs`, so we should be able to write a unit test that catches this bug? Unit tests have value additional to your script since they can be easily automated.

YES!

Let me add tests directly to the source - #522 does this.

File: src/ctap/mod.rs (hunk 1 above)
Comment (liamjm) [reply src/ctap/mod.rs]: Done.

**Comment by liamjm** [comment]
> > #520 is merged! I had a high-level comment about this PR, but I can't find it, so maybe it got lost: The fix is in `src/ctap/mod.rs`, so we should be able to write a unit test that catches this bug? Unit tests have value additional to your script since they can be easily automated.
> 
> YES!
> 
> Let me add tests directly to the source - #522 does this.

As suggested there, I've added the tests directly to this PR.

**Review by kaczmarczyck — APPROVED** [review]
